### ISSUE TITLE
雷达点的数据维度不对

### ISSUE THREAD

**Issue by bdufhus** [yuanliangxie/A-data-processing-mechanism-for-radar-and-camera-data-fusion#4]
assert points.shape[0] == self.nbr_dims(), 'Error: Pointcloud points must have format: %d x n' % self.nbr_dims()
AssertionError: Error: Pointcloud points must have format: 18 x n
您好！我用的是v1.0mini的数据集，然后出现上面的bug,检查后发现有个维度是21×74的，请问这是什么原因呢，又该如何解决呢？谢谢！

**Comment by yuanliangxie** [comment]
You could see the closed issue:[issue1](https://github.com/yuanliangxie/nuscenes_data_process/issues/1)
or you can try to comment out the Assertion sentence in **nuscenes** package where the wrong is reports, just ignore it!

**Comment by bdufhus** [comment]
Traceback (most recent call last):
  File "D:/PyCharm Community Edition 2022.2.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/NusceneStudy/nuscenes_data_process-master/nuscenes_data_process-master/radar_fusion_generator/fusion_generator.py", line 492, in <module>
    image_pure = cv2.cvtColor(image_pure, cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
您好，这个问题又有什么好的解决方法呢？十分感谢！

**Comment by yuanliangxie** [comment]
I haven't encountered this error before，so please check the input data source。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月7日(周六) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuanliangxie/nuscenes_data_process] 雷达点的数据维度不对 (Issue #4)




 
Traceback (most recent call last):
 File "D:/PyCharm Community Edition 2022.2.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
 pydev_imports.execfile(file, globals, locals)  # execute the script
 File "D:\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
 exec(compile(contents+"\n", file, 'exec'), glob, loc)
 File "D:/NusceneStudy/nuscenes_data_process-master/nuscenes_data_process-master/radar_fusion_generator/fusion_generator.py", line 492, in 
 image_pure = cv2.cvtColor(image_pure, cv2.COLOR_RGB2BGR)
 cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
 您好，这个问题又有什么好的解决方法呢？十分感谢！

**Comment by bdufhus** [comment]
谢谢，我已经解决问题了！
